import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { ConnectButton } from "@rainbow-me/rainbowkit";
import Link from 'next/link';
import Hero from '../components/main/Hero';
import { Dapp } from '../components/Dapp';
import Footer from '../components/main/Footer';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Waste2Earn DApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet"></link>
      </Head>

      <main className='bg-[#030014]'>
        <div className="w-full fixed top-0 shadow-lg shadow-[#2A0E61]/50 bg-[#03001417] backdrop-blur-md z-50 px-10">
          <div className="w-full h-full flex flex-row items-center justify-between m-auto px-[10px]">
            <div className="h-auto w-auto flex flex-row items-center cursor-pointer">
              <Link href="/">
                <Image
                  src="/logo160.png"
                  alt="logo"
                  width={90}
                  height={90}
                  className="cursor-pointer hover:animate-slowspin"
                />
              </Link>
              <span className="font-bold ml-[10px] hidden md:block text-gray-300">
                Waste2Earn
              </span>
            </div>

            <div className="flex items-center">
              <ConnectButton />
            </div>
          </div>
        </div>
        <Hero />
        {/* <Dapp /> */}
      </main>

      <Footer />
    </div>
  )
}

export default Home
